print(''.join(a))
# print(a[2])
# a.insert(3,'w')
# print(''.join(a))
# a.pop()
# print(''.join(a))
# a.remove('q')
# print(''.join(a))
# a.extend(['d','f','g','a'])
# print(''.join(a))
# a.reverse()
# print(''.join(a))
# print(len(a))

# a.append('x')
# print(a)
